#!/usr/bin/env bash
# Displays To infinity and beyond indefinitely
# and displays a msg when receiving a signal

signal()
{
    echo "I am invincible!!!"
}
trap "signal" SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done

