#!/usr/bin/env bash
# displays numbers from 1 to 100 is mul of 3 and 5 display fizzbuzz
# if mul of 3 display fizz, if mul of 5 display buzz

for (( i=1; i < 101; i++ ))
do
    if (( i % 15 == 0 )); then
	echo "FizzBuzz"
    elif (( i % 3 == 0 )); then
	echo "Fizz"
    elif (( i % 5 == 0 )); then
	echo "Buzz"
    else
	echo "$i"
    fi
done
