#!/usr/bin/env bash
# Prints numbers from 1 - 20, with some cases in between

i=1
while [ "$i" -le 20 ]
do
  # extract the file extension

  case "$i" in

    4)
      echo "4" && echo "bad luck from China"
      ;;

    9)
      echo "9" && echo "bad luck from Japan"
      ;;

    17)
      echo "17" && echo "bad luck from Italy"
      ;;

    *)
      echo "$i"
      ;;
  esac
  (( i++ ))
done
